INSERT INTO gifts
VALUES (DEFAULT, 'Apple', 'Apple Gift Card', 5, DEFAULT),
       (DEFAULT, 'Apple', 'Apple Gift Card', 10, DEFAULT),
       (DEFAULT, 'Apple', 'Apple Gift Card', 15, DEFAULT),
       (DEFAULT, 'Apple', 'Apple Gift Card', 25, DEFAULT),
       (DEFAULT, 'Apple', 'Apple Gift Card', 50, DEFAULT),
       (DEFAULT, 'Steam', 'Steam Gift Card', 5, DEFAULT),
       (DEFAULT, 'Steam', 'Steam Gift Card', 10, DEFAULT),
       (DEFAULT, 'Steam', 'Steam Gift Card', 15, DEFAULT),
       (DEFAULT, 'Steam', 'Steam Gift Card', 25, DEFAULT),
       (DEFAULT, 'Steam', 'Steam Gift Card', 50, DEFAULT),
       (DEFAULT,
        'PlayStation',
        'PlayStation Gift Card',
        5,
        DEFAULT),
       (DEFAULT,
        'PlayStation',
        'PlayStation Gift Card',
        10,DEFAULT),
       (DEFAULT,
        'PlayStation',
        'PlayStation Gift Card',
        15,DEFAULT),
       (DEFAULT,
        'PlayStation',
        'PlayStation Gift Card',
        25,DEFAULT),
       (DEFAULT,
        'PlayStation',
        'PlayStation Gift Card',
        50,DEFAULT),
       (DEFAULT, 'Spotify', 'Spotify Gift Card', 5,DEFAULT),
       (DEFAULT, 'Spotify', 'Spotify Gift Card', 10,DEFAULT),
       (DEFAULT, 'Spotify', 'Spotify Gift Card', 15,DEFAULT),
       (DEFAULT, 'Spotify', 'Spotify Gift Card', 25,DEFAULT),
       (DEFAULT, 'Spotify', 'Spotify Gift Card', 50,DEFAULT),
       (DEFAULT, 'Netflix', 'Netflix Gift Card', 5,DEFAULT),
       (DEFAULT, 'Netflix', 'Netflix Gift Card', 10,DEFAULT),
       (DEFAULT, 'Netflix', 'Netflix Gift Card', 15,DEFAULT),
       (DEFAULT, 'Netflix', 'Netflix Gift Card', 25,DEFAULT),
       (DEFAULT, 'Netflix', 'Netflix Gift Card', 50,DEFAULT);